version = 0.1

[default.deploy.parameters]
stack_name = "simplifynext-dev"
resolve_s3 = true
s3_prefix = "simplifynext-dev"
region = "us-east-1"
profile = "simplifynext"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseStubModels=\"true\""
image_repositories = ["RunCycleFunction=811405442313.dkr.ecr.us-east-1.amazonaws.com/simplifynextdev400c0f8e/runcyclefunctionb281d5c1repo", "AnalystFunction=811405442313.dkr.ecr.us-east-1.amazonaws.com/simplifynextdev400c0f8e/analystfunctionce988607repo", "ContentFunction=811405442313.dkr.ecr.us-east-1.amazonaws.com/simplifynextdev400c0f8e/contentfunction4152b2c1repo"]

[default.global.parameters]
region = "us-east-1"
